Magnetic induction solver
LKM-code-base/RotatingMHD pull request #171
Opened 2021-09-26 13:16 UTC by j507

This pull-request introduces the structure of the magnetic induction solver. 

To-do
- [ ] Add assembly methods
- [ ] Set boundary conditions for the pseudo pressure and the auxiliary scalar
- [ ] Revise and add documentation

2021-12-20 13:53 UTC, sebglane requested changes
Only minor changes.

- My major request is to check whether the inclusion of the terms involving div(v) and div(B) is really necessary. I don't think that I have seen in the publications of other authors. Could you comment on this.
- I have not check all of the boiler-plate code.

2021-12-20 13:53 UTC, sebglane commented on include/rotatingMHD/assembly_data.h
> +  std::vector<curl_type>      old_old_magnetic_field_curls;
Why are the curls required?

2021-12-20 13:53 UTC, sebglane commented on include/rotatingMHD/assembly_data.h
> +  std::vector<double>         old_old_magnetic_field_divergences;
Why are the divergences required?

2021-12-20 13:53 UTC, sebglane commented on include/rotatingMHD/assembly_data.h
> +  std::vector<double>         old_old_velocity_divergences;
Same here. Why is this required?

2021-12-20 13:53 UTC, sebglane commented on include/rotatingMHD/assembly_data.h
> +  std::vector<curl_type>      curl_phi;
Why is this required?

2021-12-20 13:53 UTC, sebglane commented on include/rotatingMHD/magnetic_induction.h
> + *    \dint{v} \\
The div(B) and div(v) should be removed because of the incompressibility constraint.

2021-12-20 13:53 UTC, sebglane commented on include/rotatingMHD/magnetic_induction.h
> + *    \Sigma^k = \Sigma^{k-1} + \Phi^k,
Please use `\sigma` instead of `\Sigma`, same for `\Phi`.

2021-12-20 13:53 UTC, sebglane commented on include/rotatingMHD/magnetic_induction.h
> + * where \f$ \Sigma\f$ and \f$ \Phi \f$ contain the nodal values of
Same here.

2021-12-20 13:53 UTC, sebglane commented on include/rotatingMHD/run_time_parameters.h
> +double  C8;
What don't we just call this coefficient `C`?

2021-12-20 13:53 UTC, sebglane commented on source/magnetic_induction/assembly_advection_matrix.cc
> +           scratch.velocity_divergences[q]
This should be removed for simplicity.

2021-12-20 13:53 UTC, sebglane commented on source/magnetic_induction/assembly_advection_matrix.cc
> +           scratch.div_phi[j]
This should be removed for simplicity. div(B) = 0.

2021-12-20 13:53 UTC, sebglane commented on source/magnetic_induction/assembly_diffusion_step_rhs.cc
> +                 (eta[0] * scratch.old_velocity_divergences[q]
This can be removed since div(v) = 0.

2021-12-20 13:53 UTC, sebglane commented on source/magnetic_induction/assembly_diffusion_step_rhs.cc
> +                 scratch.div_phi[i]
This can be removed since div(B) = 0.

2021-12-20 13:53 UTC, sebglane commented on source/magnetic_induction/assembly_diffusion_step_rhs.cc
> +          scratch.old_magnetic_field_divergences[q]
This can be removed since div(B) = 0.

2021-12-20 13:53 UTC, sebglane commented on source/magnetic_induction/assembly_diffusion_step_rhs.cc
> +          trace(scratch.velocity_gradients[q])
This can be removed since div(v) = 0.

2021-12-20 13:53 UTC, sebglane commented on source/magnetic_induction/assembly_diffusion_step_rhs.cc
> +          scratch.old_old_magnetic_field_divergences[q]
This can be removed since div(B) = 0.

2021-12-20 13:53 UTC, sebglane commented on source/magnetic_induction/assembly_diffusion_step_rhs.cc
> +          trace(scratch.velocity_gradients[q])
This can be removed since div(v) = 0.

2021-12-20 13:53 UTC, sebglane commented on source/magnetic_induction/assembly_diffusion_step_rhs.cc
> +          scratch.old_magnetic_field_divergences[q]
This can be removed since div(B) = 0.

2021-12-20 13:53 UTC, sebglane commented on source/magnetic_induction/assembly_diffusion_step_rhs.cc
> +          scratch.old_old_magnetic_field_divergences[q]
This can be removed since div(B) = 0.

2021-12-20 13:53 UTC, sebglane commented on source/magnetic_induction/assembly_diffusion_step_rhs.cc
> +          scratch.old_old_velocity_divergences[q]
This can be removed since div(v) = 0.

2021-12-20 13:53 UTC, sebglane commented on source/magnetic_induction/assembly_advection_matrix.cc
> +           scratch.phi[j]
I would move this term to the right-hand side and interpret it as a _source term_.

2021-12-20 13:53 UTC, sebglane commented on include/rotatingMHD/magnetic_induction.h
> + *    \cdot (\nabla \otimes \bs{v}^{k-j}) -
I would move this term to the right-hand side and interpret it as a _source term_.

2021-12-20 13:53 UTC, sebglane commented on source/magnetic_induction/assembly_diffusion_step_rhs.cc
> +          scratch.old_velocity_divergences[q]
This can be removed since div(v) = 0.

2021-12-20 13:53 UTC, sebglane commented on source/magnetic_induction/assembly_diffusion_step_rhs.cc
> +          scratch.old_velocity_values[q])
I would interpret this term as a _source term_.

2021-12-20 13:53 UTC, sebglane commented on source/magnetic_induction/assembly_diffusion_step_rhs.cc
> +                 scratch.velocity_values[q]) *
Aren't `beta[0]` and `beta[1]` missing here?

2021-12-20 13:53 UTC, sebglane commented on source/magnetic_induction/assembly_diffusion_step_rhs.cc
> +                 scratch.div_phi[i]
This can be removed since div(B) = 0.

2021-12-20 13:53 UTC, sebglane commented on source/magnetic_induction/assembly_diffusion_step_rhs.cc
> +                 scratch.velocity_divergences[q]
This can be removed since div(v) = 0.

2021-12-20 13:53 UTC, sebglane commented on source/magnetic_induction/assembly_diffusion_step_rhs.cc
> +                 scratch.velocity_values[q]) *
I would interpret this term as a _source term_.

2021-12-20 13:53 UTC, sebglane commented on include/rotatingMHD/magnetic_induction.h
> + * (\nabla \cdot \boldsymbol{\mathfrak{B}}^{k}) \bs{v}^{k}
This can be removed since div(B) = 0.

2021-12-20 13:53 UTC, sebglane commented on include/rotatingMHD/magnetic_induction.h
> + * (\nabla \cdot \bs{v}^{k}) \boldsymbol{\mathfrak{B}}^{k}
This can be removed since div(v) = 0.

2021-12-20 13:53 UTC, sebglane commented on include/rotatingMHD/magnetic_induction.h
> + * \boldsymbol{\mathfrak{B}}^{k} \cdot (\nabla \otimes \bs{v}^{k})
I would interpret this term as a _source term_ and move it to the right-hand side.

2021-12-20 13:53 UTC, sebglane commented on source/magnetic_induction/setup.cc
> +                            "conditions are currently being supported "
_are currently supported_ sounds better

2021-12-23 19:00 UTC, j507 commented
> Only minor changes.
> 
>     * My major request is to check whether the inclusion of the terms involving div(v) and div(B) is really necessary. I don't think that I have seen in the publications of other authors. Could you comment on this?

My reasoning was that, as the fields are not really divergence-free, the addition of the terms makes sure the that tensor identities hold

>     * I have not check all of the boiler-plate code. Do you think that this is necessary?

Just to be sure, which code do you classify as boiler-plate? If you mean all that is just copy-paste from other code snippets, then no. 

>     * Let me know whether I should implement the changes. I have some spare time during this week.

I should have more spare time from tomorrow until the 31th and I will try to wrap up these pull-requests. From the 31th to the 18th I won't be in Berlin. I will take a laptop with me so I could still review pull-requests but I don't think that I will have to time for coding.

2022-01-03 09:40 UTC, sebglane commented
> My reasoning was that, as the fields are not really divergence-free, the addition of the terms makes sure the that tensor identities hold

Yes, the fields are not divergence free because of the spatio-temporal discretization. However, this is usually ignored in order not to pollute the time evolution by additional artifacts. I will remove the corresponding terms.

2022-01-03 09:42 UTC, sebglane commented
> Just to be sure, which code do you classify as boiler-plate? If you mean all that is just copy-paste from other code snippets, then no.

I refer to the additional parameter structures and assembly structures, constructors etc.

2022-01-03 16:55 UTC, sebglane commented on include/rotatingMHD/assembly_data.h
> +  std::vector<curl_type>      old_old_magnetic_field_curls;
They are required because they occur in the diffusion term.

2022-01-03 16:56 UTC, sebglane commented on include/rotatingMHD/run_time_parameters.h
> +double  C8;
Changed.

2022-01-04 16:51 UTC, sebglane approved these changes
I decided to keep [the term](http://www.texrendr.com/?eqn=%5Cboldsymbol%7BB%7D%5Ccdot%5Cnabla%5Cotimes%5Cboldsymbol%7Bv%7D) as a transport term and discarded the idea to treat it as a source term. However, tests will be necessary.

2022-01-04 17:01 UTC, merged